title: Site
# preset: pages
# unlisted: true

tabs:
  pages:
    label: Pages
    icon: page
    columns:
      - width: 1/2
        sections:
          pages:
            type: pages
            headline: Pages
  settings:
    label: Paramètres
    icon: settings
    columns:
      - width: 1/3
        sections:
          images:
            type: files
            template: image
            info: "{{ file.dimensions }}"
            size: small
      - width: 1/2
        fields:
          logo: 
            label: Logo du site
            type: files
            multiple: false
          menu: 
            label: Organisation du menu 
            type: headline
          groupe1: 
            label: Groupe 1
            type: checkboxes
            options: query
            query: site.children.listed
            help: Cocher les pages appartenant au premier groupe du menu
          groupe2: 
            label: Groupe 2
            type: checkboxes
            options: query
            query: site.children.listed
            help: Cocher les pages appartenant au deuxième groupe du menu 
          groupe3: 
            label: Groupe 3
            type: checkboxes
            options: query
            query: site.children.listed
            help: Cocher les pages appartenant au troisième groupe du menu 
          groupe4: 
            label: Groupe 4
            type: checkboxes
            options: query
            query: site.children.listed
            help: Cocher les pages appartenant au quatrième groupe du menu 
          groupe5: 
            label: Groupe 5
            type: checkboxes
            options: query
            query: site.children.listed
            help: Cocher les pages appartenant au cinquième groupe du menu 
          old: 
            label: Ancien Site
            type: textarea
          config: 
            label: Configuration du site
            type: headline
          author: 
            label: Auteur
            type: text
          keywords:
            label: Mots-clés (pour les moteurs de recherche)
            type: tags
          description: 
            label: Description (pour les moteurs de recherche)
            type: textarea
            size: small
          copyright: 
            label: Copyright
            type: text


